services:
  postgres_customer:
    container_name: postgres_customer
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgres/data
    volumes:
      - postgres_customer:/var/lib/postgres/data
    ports:
      - "5532:5432"
    networks:
      - postgres
    restart: unless-stopped

  postgres_fraud:
    container_name: postgres_fraud
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgres/data
    volumes:
      - postgres_fraud:/var/lib/postgres/data
    ports:
      - "5533:5432"
    networks:
      - postgres
    restart: unless-stopped

  postgres_notifications:
    container_name: postgres_notifications
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgres/data
    volumes:
      - postgres_notifications:/var/lib/postgres/data
    ports:
      - "5534:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

networks:
  postgres:
    driver: bridge

volumes:
  postgres_customer:
  postgres_fraud:
  postgres_notifications:
  pgadmin: